version: '3.8'

services:
  # MongoDB for development
  mongodb-dev:
    image: mongo:7.0
    container_name: agent-management-db-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-agent-management}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - agent-management-dev-network

  # Development server with hot reload
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: agent-management-app-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb-dev:27017/${MONGO_DB_NAME:-agent-management}
      JWT_SECRET: ${JWT_SECRET:-dev-jwt-secret}
      PORT: 5000
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-5242880}
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173
    ports:
      - "${APP_PORT:-5000}:5000"
    volumes:
      - ./server:/app/server
      - ./package.json:/app/package.json
      - app_dev_uploads:/app/uploads
      - app_dev_logs:/app/logs
      - /app/server/node_modules
    networks:
      - agent-management-dev-network
    depends_on:
      - mongodb-dev
    command: npm run server:dev

  # Client development server
  client-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: agent-management-client-dev
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - agent-management-dev-network
    command: npm run dev -- --host 0.0.0.0

volumes:
  mongodb_dev_data:
    driver: local
  app_dev_uploads:
    driver: local
  app_dev_logs:
    driver: local

networks:
  agent-management-dev-network:
    driver: bridge